#!/usr/bin/env python3
"""Generate the embedded asset C header from the canonical asset files."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def load_manifest(path: Path) -> list[dict[str, object]]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read manifest {path}: {exc}")
    assets = payload.get("assets")
    if payload.get("version") != 1 or not isinstance(assets, list) or not assets:
        fail(f"invalid manifest format: {path}")
    return assets


def validate_symbol(symbol: str) -> None:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", symbol):
        fail(f"invalid C symbol in manifest: {symbol!r}")


def c_bytes(data: bytes, width: int = 24) -> str:
    rows = []
    for offset in range(0, len(data), width):
        chunk = data[offset : offset + width]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(rows)


def generate(manifest_path: Path, asset_root: Path, output: Path) -> None:
    assets = load_manifest(manifest_path)
    seen_names: set[str] = set()
    seen_symbols: set[str] = set()
    blocks: list[str] = []
    table_rows: list[str] = []

    for entry in assets:
        if not isinstance(entry, dict):
            fail("manifest asset entry is not an object")
        name = entry.get("name")
        rel = entry.get("path")
        symbol = entry.get("symbol")
        expected_hash = entry.get("sha256")
        expected_size = entry.get("size")
        if not all(isinstance(value, str) for value in (name, rel, symbol, expected_hash)):
            fail(f"invalid manifest asset entry: {entry!r}")
        if not isinstance(expected_size, int) or expected_size < 0:
            fail(f"invalid asset size for {rel}")
        validate_symbol(symbol)
        if name in seen_names or symbol in seen_symbols:
            fail(f"duplicate asset name or symbol: {name} / {symbol}")
        seen_names.add(name)
        seen_symbols.add(symbol)

        source = (asset_root / rel).resolve()
        try:
            source.relative_to(asset_root.resolve())
        except ValueError:
            fail(f"asset path escapes resource root: {rel}")
        try:
            data = source.read_bytes()
        except OSError as exc:
            fail(f"cannot read asset {rel}: {exc}")

        actual_hash = hashlib.sha256(data).hexdigest()
        if len(data) != expected_size or actual_hash != expected_hash:
            fail(
                f"asset integrity mismatch: {rel}\n"
                f"  expected: {expected_size} bytes / {expected_hash}\n"
                f"  actual:   {len(data)} bytes / {actual_hash}"
            )

        blocks.append(
            f"static const unsigned char {symbol}[] = {{\n"
            f"{c_bytes(data)}\n"
            f"}};\n"
        )
        escaped_name = name.replace("\\", "\\\\").replace('"', '\\"')
        escaped_rel = rel.replace("*/", "* /")
        table_rows.append(
            f'    {{"{escaped_name}", {symbol}, sizeof({symbol})}}, /* {escaped_rel} */'
        )

    header = "\n".join(
        [
            "#ifndef SNOW_LEOPARD_EMBEDDED_ASSETS_H",
            "#define SNOW_LEOPARD_EMBEDDED_ASSETS_H",
            "",
            "/* AUTO-GENERATED by scripts/generate-embedded-assets.py. DO NOT EDIT. */",
            "",
            "#include <stddef.h>",
            "#include <string.h>",
            "",
            "typedef struct {",
            "    const char *name;",
            "    const unsigned char *bytes;",
            "    size_t length;",
            "} SLEmbeddedAsset;",
            "",
            *blocks,
            "static const SLEmbeddedAsset SLEmbeddedAssets[] = {",
            *table_rows,
            "};",
            "",
            "static const size_t SLEmbeddedAssetCount =",
            "    sizeof(SLEmbeddedAssets) /",
            "    sizeof(SLEmbeddedAssets[0]);",
            "",
            "static inline const SLEmbeddedAsset *SLEmbeddedAssetNamed(const char *name) {",
            "    if (!name) return NULL;",
            "    for (size_t index = 0; index < SLEmbeddedAssetCount; index++) {",
            "        if (strcmp(SLEmbeddedAssets[index].name, name) == 0) return &SLEmbeddedAssets[index];",
            "    }",
            "    return NULL;",
            "}",
            "",
            "#endif",
            "",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    # Path.write_text(newline=...) is only available on newer Python releases.
    # Use Path.open() so the generator also works with the Python 3.9 commonly
    # available on supported macOS installations.
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(header)
    temporary.replace(output)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("asset_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.manifest, args.asset_root, args.output)


if __name__ == "__main__":
    main()
